plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md


# Theme: Just the Docs
# https://pmarsceill.github.io/just-the-docs/
remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
    "Repository on GitHub":
      - "//github.com/ekeoid/ekeoid.github.io"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil
